start =
	expression

validchar = [0-9a-zA-Z_?!+\-=@#$%^&*/.]

atom =  chars:validchar+
	{ return chars.join("");}
   
whitespace = [ \t\n]

spacedexpression = whitespace+ e:expression
	{ return e; }
   
exprlist = whitespace* "(" whitespace* e:expression el:spacedexpression* whitespace* ")" whitespace*
	{ return [e].concat(el); }
 
expression = whitespace* a:atom
	{ return a; }
        / el:exprlist
    	{ return el; }
