start =
	expression

validchar = [0-9a-zA-Z_?!+\-=@#$%^&*/.]

atom =  chars:validchar+
	{ return chars.join("");}
 
spacedexpression = whitespace+ e:expression
	{ return e; }
   
exprlist = ignored "(" ignored e:expression el:spacedexpression* ignored ")" ignored 
	{ return [e].concat(el); }
 
expression = ignored a:atom
	{ return a; }
        / el:exprlist
    	{ return el; }

comment = ";;" (!newline .)*
newline = [\r\n]
whitespace = [\t ]
ignored = (newline / whitespace / comment)*
